# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be8e17d058f6e92a13e86547314c0e612b1a22833d8179ff9474fa994bfde32591e59c3035db4b9c2acfc2d6598c7dad862fa11982b7a7dac175fdcf7202f78

test:
  secret_key_base: fd3d2db79d5e634cd7c931896bbe55f5af7edf35f4823d8e4a8c2c396ef2d55e1257e5292790236156a0b204ec9a093b63676627332417740e117b4c1fec820e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
